### ISSUE TITLE
Q: Japanese translation/publication plan

### ISSUE THREAD

**Issue by ktgw0316** [ktgw0316/milewski-ctfp-markdown#2]
@BartoszMilewski
Dear Dr. Bartosz Milewski,

I recently did a Japanese translation of your "Category Theory for Programmers".
After finishing the translation, I noticed the following comment on your blog:
https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface/#comment-95081

So, I have some question:
1. Do you have any current plan to publish a Japanese translation of your blog post as a book?
2. Is there any problem with keeping my version public?  I hope this is not a problem, since you released your work under CC-BY license, but I just want to make sure.

By the way, thank you very much for your great work!

**Comment by BartoszMilewski** [comment]
I don't have any publishing plans. Please don't hesitate to keep your translation public.

**Comment by ktgw0316** [comment]
@BartoszMilewski
Thank you very much for your reply.

I hope to publish this book in Japan one day in both e-book and paper book form, although I have no plan yet.  I'll ask for your permission again when it is realized.

**Comment by ktgw0316** [comment]
@BartoszMilewski
A Japanese publishing company is planning to publish the translated version as a book (both paper book and e-book), so I would like to ask for your permission. Specifically, the publisher wants to make sure whether or not they have to pay the original author.

@hmemcpy
My work is based on the PDF version you published, so I would also like to ask for your permission.

Again, I hope this is not a problem, since it is under CC-BY license. I would appreciate your understanding.

**Comment by hmemcpy** [comment]
Hello!
I really know little about these things "legally" speaking, but the original content is CC-BY-SA, so it permits commercial use. The only requirement, I believe, is attribution to the original Author.
From my point of view there's absolutely no problem, and I would personally be happy to see this work translated into more languages :)

**Comment by BartoszMilewski** [comment]
Hello,
The book is public domain, and I have no problem with it being published in Japanese. I don't expect to be paid for it either.
--Bartosz Milewski

**Comment by ktgw0316** [comment]
@BartoszMilewski @hmemcpy
Thank you very much for your kind words!
