### ISSUE TITLE
One moves the eggs, the other boils them

### ISSUE THREAD

**Issue by ktgw0316** [ktgw0316/milewski-ctfp-markdown#31]
Hello @BartoszMilewski,

What is the source of the quote “One moves the eggs, the other boils them” in chapter 10? Is it your original?
If there is an original source, I would like to mention it in the translator's note.

(LLM on poe.com [said](https://poe.com/s/RT4LWhKMFLKfBdlHp8Ou) it was a quote from *Don Quixote*, but I don't think that's true.)

**Comment by BartoszMilewski** [comment]
I think I came up with it myself.

**Comment by ktgw0316** [comment]
Thank you!
